run:
  deadline: 5m
  skip-dirs:
    - "vta_ms_form_green_package"

linters:
  enable-all: true
  disable:
    - maligned
    - interfacer
    - scopelint
    - gomoddirectives
    - nolintlint
    - exhaustivestruct
    - gochecknoinits
    - varnamelen
    - ireturn
    - gochecknoglobals
    - goerr113
    - golint
    - tagliatelle
    - wrapcheck
    - gomnd
    - paralleltest
    - wsl
    - exhaustruct
    - nonamedreturns
    - gofumpt
    - nlreturn
    - cyclop
    - exhaustruct
    - godox
    - revive
    - godot
    - gci